from pathlib import Path
from datetime import datetime
from rich.console import Console

console = Console()

def _fmt(val) -> str:
	if val is None:
		return "N/A"
	if isinstance(val, float):
		if abs(val) < 0.01:
			return f"{val:.4f}"
		if abs(val) < 100:
			return f"{val:.2f}"
		return f"{val:,.0f}"
	if isinstance(val, int):
		return f"{val:,}"
	return str(val)

def _fmt_delta(before, after) -> str:
	if before is None or after is None:
		return "—"
	if not isinstance(before, (int, float)):
		return "—"
	diff = after - before
	if abs(diff) < 0.01 and isinstance(before, float):
		return "≈"
	sign = "↑" if diff > 0 else "↓" if diff < 0 else "•"
	val = f"{abs(diff):.2f}" if isinstance(before, float) else f"{int(abs(diff)):,}"
	return f"{sign} {val}"

def generate_report(before: dict, after: dict, stats: dict, out_path: str):
	p = Path(out_path)
	p.parent.mkdir(parents=True, exist_ok=True)

	ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
	inp = stats.get("input", "N/A")
	out = stats.get("output", "N/A")

	md = f"""# 📊 TextDataBench Report
**Generated:** {ts}
**Input:** `{inp}` → **Output:** `{out}`
**Steps Completed:** {stats.get('steps_completed', 0)}/4

---

## 📈 Pipeline Summary
| Metric                     |     Value |
|:---------------------------|----------:|
| Rows Processed             | {_fmt(after.get('rows', 0))} |
| Dedup Removed              | {_fmt(before.get('rows', 0) - after.get('rows', 0))} |
| Avg Length (chars)         | {_fmt(after.get('avg_chars', 0))} |
| Avg Tokens                 | {_fmt(after.get('avg_tokens', 0))} |
| TTR (Lexical Diversity)    | {_fmt(after.get('ttr', 0))} |
| Shannon Entropy            | {_fmt(after.get('shannon_entropy', 0))} |
| Empty Ratio                | {_fmt(after.get('empty_ratio', 0))} |

---

## 🔄 Metric Delta (Before → After)
| Metric               |     Before |      After |   Change |
|:---------------------|-----------:|-----------:|---------:|
"""

	metrics = [
		("rows", "Rows"),
		("avg_chars", "Avg Chars"),
		("max_chars", "Max Chars"),
		("avg_tokens", "Avg Tokens"),
		("ttr", "TTR"),
		("shannon_entropy", "Entropy"),
		("empty_ratio", "Empty %"),
	]

	for key, label in metrics:
		b, a = before.get(key), after.get(key)
		md += f"| {label:<20} | {_fmt(b):>12} | {_fmt(a):>12} | {_fmt_delta(b, a):>10} |\n"

	md += "\n---\n*Generated by TextDataBench v1.1.0*\n"
	p.write_text(md, encoding="utf-8")
	console.print(f"[green]✓ Report saved: {p}[/green]")
